/**
 * Salesforce Connector Configuration
 *
 * This file is auto-generated by the setup wizard.
 * You can also edit it manually to add/remove objects.
 */

export interface SalesforceField {
  apiName: string; // Salesforce API name (e.g., "FirstName")
  convexName: string; // Convex field name (e.g., "firstName")
  type: "string" | "number" | "boolean" | "date" | "datetime" | "any";
  required?: boolean;
  index?: boolean; // Create an index on this field
}

export interface SalesforceObject {
  apiName: string; // Salesforce object API name (e.g., "Contact", "Custom__c")
  tableName: string; // Convex table name (e.g., "sfContacts", "sfCustom")
  label: string; // Display label
  enabled: boolean;
  fields: SalesforceField[];
}

/**
 * Default configuration for standard Salesforce objects.
 * Customize this or run the setup wizard to configure.
 */
export const SALESFORCE_OBJECTS: SalesforceObject[] = [
  {
    apiName: "Account",
    tableName: "sfAccounts",
    label: "Accounts",
    enabled: true,
    fields: [
      { apiName: "Name", convexName: "name", type: "string", required: true },
      { apiName: "Type", convexName: "type", type: "string" },
      { apiName: "ParentId", convexName: "parentId", type: "string" },
      { apiName: "BillingStreet", convexName: "billingStreet", type: "string" },
      { apiName: "BillingCity", convexName: "billingCity", type: "string" },
      { apiName: "BillingState", convexName: "billingState", type: "string" },
      { apiName: "BillingPostalCode", convexName: "billingPostalCode", type: "string" },
      { apiName: "BillingCountry", convexName: "billingCountry", type: "string" },
      { apiName: "ShippingStreet", convexName: "shippingStreet", type: "string" },
      { apiName: "ShippingCity", convexName: "shippingCity", type: "string" },
      { apiName: "ShippingState", convexName: "shippingState", type: "string" },
      { apiName: "ShippingPostalCode", convexName: "shippingPostalCode", type: "string" },
      { apiName: "ShippingCountry", convexName: "shippingCountry", type: "string" },
      { apiName: "Phone", convexName: "phone", type: "string", index: true },
      { apiName: "Website", convexName: "website", type: "string" },
      { apiName: "Industry", convexName: "industry", type: "string" },
      { apiName: "AnnualRevenue", convexName: "annualRevenue", type: "number" },
      { apiName: "NumberOfEmployees", convexName: "numberOfEmployees", type: "number" },
      { apiName: "Description", convexName: "description", type: "string" },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
  {
    apiName: "Contact",
    tableName: "sfContacts",
    label: "Contacts",
    enabled: true,
    fields: [
      { apiName: "AccountId", convexName: "accountId", type: "string", index: true },
      { apiName: "FirstName", convexName: "firstName", type: "string" },
      { apiName: "LastName", convexName: "lastName", type: "string", required: true },
      { apiName: "Name", convexName: "name", type: "string", required: true },
      { apiName: "Salutation", convexName: "salutation", type: "string" },
      { apiName: "Title", convexName: "title", type: "string" },
      { apiName: "MailingStreet", convexName: "mailingStreet", type: "string" },
      { apiName: "MailingCity", convexName: "mailingCity", type: "string" },
      { apiName: "MailingState", convexName: "mailingState", type: "string" },
      { apiName: "MailingPostalCode", convexName: "mailingPostalCode", type: "string" },
      { apiName: "MailingCountry", convexName: "mailingCountry", type: "string" },
      { apiName: "Phone", convexName: "phone", type: "string", index: true },
      { apiName: "MobilePhone", convexName: "mobilePhone", type: "string", index: true },
      { apiName: "Email", convexName: "email", type: "string", index: true },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
  {
    apiName: "Lead",
    tableName: "sfLeads",
    label: "Leads",
    enabled: true,
    fields: [
      { apiName: "FirstName", convexName: "firstName", type: "string" },
      { apiName: "LastName", convexName: "lastName", type: "string", required: true },
      { apiName: "Name", convexName: "name", type: "string", required: true },
      { apiName: "Company", convexName: "company", type: "string" },
      { apiName: "Street", convexName: "street", type: "string" },
      { apiName: "City", convexName: "city", type: "string" },
      { apiName: "State", convexName: "state", type: "string" },
      { apiName: "PostalCode", convexName: "postalCode", type: "string" },
      { apiName: "Country", convexName: "country", type: "string" },
      { apiName: "Phone", convexName: "phone", type: "string", index: true },
      { apiName: "Email", convexName: "email", type: "string", index: true },
      { apiName: "Website", convexName: "website", type: "string" },
      { apiName: "Status", convexName: "status", type: "string", index: true },
      { apiName: "LeadSource", convexName: "leadSource", type: "string" },
      { apiName: "IsConverted", convexName: "isConverted", type: "boolean" },
      { apiName: "ConvertedAccountId", convexName: "convertedAccountId", type: "string" },
      { apiName: "ConvertedContactId", convexName: "convertedContactId", type: "string" },
      { apiName: "ConvertedOpportunityId", convexName: "convertedOpportunityId", type: "string" },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
  {
    apiName: "Opportunity",
    tableName: "sfOpportunities",
    label: "Opportunities",
    enabled: true,
    fields: [
      { apiName: "AccountId", convexName: "accountId", type: "string", index: true },
      { apiName: "Name", convexName: "name", type: "string", required: true },
      { apiName: "Description", convexName: "description", type: "string" },
      { apiName: "StageName", convexName: "stageName", type: "string", required: true, index: true },
      { apiName: "Amount", convexName: "amount", type: "number" },
      { apiName: "Probability", convexName: "probability", type: "number" },
      { apiName: "CloseDate", convexName: "closeDate", type: "date", index: true },
      { apiName: "Type", convexName: "type", type: "string" },
      { apiName: "LeadSource", convexName: "leadSource", type: "string" },
      { apiName: "IsClosed", convexName: "isClosed", type: "boolean" },
      { apiName: "IsWon", convexName: "isWon", type: "boolean" },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
  {
    apiName: "Task",
    tableName: "sfTasks",
    label: "Tasks",
    enabled: false, // Disabled by default
    fields: [
      { apiName: "WhoId", convexName: "whoId", type: "string", index: true },
      { apiName: "WhatId", convexName: "whatId", type: "string", index: true },
      { apiName: "Subject", convexName: "subject", type: "string" },
      { apiName: "Description", convexName: "description", type: "string" },
      { apiName: "Status", convexName: "status", type: "string", index: true },
      { apiName: "Priority", convexName: "priority", type: "string" },
      { apiName: "ActivityDate", convexName: "activityDate", type: "date" },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
  {
    apiName: "Event",
    tableName: "sfEvents",
    label: "Events",
    enabled: false, // Disabled by default
    fields: [
      { apiName: "WhoId", convexName: "whoId", type: "string", index: true },
      { apiName: "WhatId", convexName: "whatId", type: "string", index: true },
      { apiName: "Subject", convexName: "subject", type: "string" },
      { apiName: "Description", convexName: "description", type: "string" },
      { apiName: "Location", convexName: "location", type: "string" },
      { apiName: "StartDateTime", convexName: "startDateTime", type: "datetime", index: true },
      { apiName: "EndDateTime", convexName: "endDateTime", type: "datetime" },
      { apiName: "IsAllDayEvent", convexName: "isAllDayEvent", type: "boolean" },
      { apiName: "OwnerId", convexName: "ownerId", type: "string", index: true },
    ],
  },
];

/**
 * Get enabled objects only
 */
export function getEnabledObjects(): SalesforceObject[] {
  return SALESFORCE_OBJECTS.filter((obj) => obj.enabled);
}

/**
 * Get object by API name
 */
export function getObjectByApiName(apiName: string): SalesforceObject | undefined {
  return SALESFORCE_OBJECTS.find((obj) => obj.apiName === apiName);
}

/**
 * Get object by table name
 */
export function getObjectByTableName(tableName: string): SalesforceObject | undefined {
  return SALESFORCE_OBJECTS.find((obj) => obj.tableName === tableName);
}

/**
 * Build SOQL field list for an object
 */
export function buildFieldList(obj: SalesforceObject): string {
  const fields = ["Id", ...obj.fields.map((f) => f.apiName), "CreatedDate", "LastModifiedDate"];
  return [...new Set(fields)].join(", ");
}

/**
 * Map Salesforce record to Convex document
 */
export function mapRecordToDocument(obj: SalesforceObject, record: Record<string, any>): Record<string, any> {
  const doc: Record<string, any> = {};

  for (const field of obj.fields) {
    const value = record[field.apiName];
    if (value !== undefined) {
      doc[field.convexName] = value === null ? undefined : value;
    }
  }

  return doc;
}
