#!/usr/bin/env node

/**
 * Generate CDC trigger for a Salesforce object
 * Usage: npm run generate:trigger ObjectName
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, '..');
const TRIGGER_DIR = join(ROOT_DIR, 'salesforce/force-app/main/default/triggers');

const objectName = process.argv[2];

if (!objectName) {
  console.log('Usage: npm run generate:trigger <ObjectName>');
  console.log('Example: npm run generate:trigger MyCustomObject__c');
  process.exit(1);
}

// Ensure trigger directory exists
if (!existsSync(TRIGGER_DIR)) {
  mkdirSync(TRIGGER_DIR, { recursive: true });
}

// Generate names
const isCustom = objectName.endsWith('__c');
const baseName = isCustom ? objectName.replace('__c', '') : objectName;
const triggerName = `${baseName}CDCTrigger`;
const eventName = isCustom ? `${baseName}__ChangeEvent` : `${objectName}ChangeEvent`;

// Check if trigger already exists
const triggerPath = join(TRIGGER_DIR, `${triggerName}.trigger`);
if (existsSync(triggerPath)) {
  console.log(`Trigger already exists: ${triggerPath}`);
  process.exit(0);
}

// Generate trigger content
const triggerContent = `/**
 * CDC Trigger for ${objectName} object
 * Auto-generated by generate-trigger script
 */
trigger ${triggerName} on ${eventName} (after insert) {
    ConvexCDCService.processChangeEvents(Trigger.new, '${objectName}');
}
`;

const metaContent = `<?xml version="1.0" encoding="UTF-8"?>
<ApexTrigger xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <status>Active</status>
</ApexTrigger>
`;

// Write files
writeFileSync(triggerPath, triggerContent);
writeFileSync(`${triggerPath}-meta.xml`, metaContent);

console.log(`✓ Generated trigger: ${triggerPath}`);
console.log(`✓ Generated meta:    ${triggerPath}-meta.xml`);
console.log(`\nNext steps:`);
console.log(`1. Enable CDC for ${objectName} in Salesforce Setup`);
console.log(`2. Deploy: sf project deploy start -d salesforce/force-app`);
